version: "3.9"

services:
  postgresdsa:
    image: postgres:14-alpine
    env_file:
      - ".env.example"
    ports:
      - "5432:5432"

  redis:
    image: redis
    environment:
      - decode_responses=True
    ports:
      - "6379:6379"

