# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11permissions.proto\x12\x0cpermissionpb\"/\n\x11PermissionRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"$\n\x12PermissionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x32\x64\n\nPermission\x12V\n\x0f\x43heckPermission\x12\x1f.permissionpb.PermissionRequest\x1a .permissionpb.PermissionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'permissions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERMISSIONREQUEST._serialized_start=35
  _PERMISSIONREQUEST._serialized_end=82
  _PERMISSIONRESPONSE._serialized_start=84
  _PERMISSIONRESPONSE._serialized_end=120
  _PERMISSION._serialized_start=122
  _PERMISSION._serialized_end=222
# @@protoc_insertion_point(module_scope)
